name: Lint & Test (Informational Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    # Make sure the workflow continues even if linting fails
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install isort
          # Alternatively if your dev dependencies are in requirements-dev.txt
          # pip install -r requirements-dev.txt
      
      - name: Run linters (Informational Only)
        run: |
          ./lint.sh --check || echo "Linting failed but continuing workflow"
  
  test:
    runs-on: ubuntu-latest
    # Make sure the workflow continues even if tests fail
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pytest pytest-cov isort
      
      - name: Run tests (Informational Only)
        run: |
          pytest --cov=frostbyte tests/ || echo "Tests failed but continuing workflow"
